# Generated by Django 5.1.6 on 2025-03-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
